from .test_compositional_classification import test_compositional_classifiers_1, test_compositional_classifiers_2, test_compositional_classifiers_3
from .test_compositional_regression import test_apply_transform_ndarray, test_apply_transform_dataframe, test_compositional_regressions_1
from .test_compositional_regression import test_compositional_regressions_2, test_compositional_regressions_3
from .test_compositional_clusterization import test_compositional_clustering
from .test_transformers import test_lr_transform_dataframe, test_lr_transform_ndarray, test_lr_transform_pipeline
